source ~/softwares/antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle git
antigen bundle command-not-found
antigen bundle per-directory-history

# other bundles
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-autosuggestions

export NVM_LAZY_LOAD=true
export NVM_COMPLETION=true
antigen bundle lukechilds/zsh-nvm

# Load the theme.
antigen theme denysdovhan/spaceship-prompt

# Tell Antigen that you're done.
antigen apply

# User configuration

# Functions
mkcd() { mkdir -p "$1" && cd "$1"; } 
fcount() { ls "$1" | wc -l }

export LANG=fr_FR.UTF-8

# Aliases
alias zshrc="vim $HOME/.zshrc"

alias rsync="rsync -Paz"

alias clr='printf "\033c"'

alias u="sudo pacman -Syu"
